# Generated by Django 5.2.11 on 2026-03-10 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0002_alter_epi_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epi',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='⚠ A quantidade deve ser maior que zero')]),
        ),
    ]
