# Generated by Django 5.2.11 on 2026-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0004_alter_epi_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epi',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
